apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: rentzone-secret
  namespace: rentzone
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:eu-west-2:216989101000:secret:rentzone-secret-POhXrT"
          objectAlias: "app-secret"